const products={
'wire-ropes':{title:'Steel Wire Ropes',page:4,summary:'Premium wire rope constructions selected for strength, flexibility and resistance to demanding operating conditions.',description:'AllSafe supplies steel wire ropes for cranes, hoists, elevators, marine operations, oil and gas and general lifting applications. Available options include galvanized and ungalvanized finishes.',features:['6×36 IWRC flexible construction','19×7 rotation-resistant construction','35×7 non-rotating construction','Galvanized and ungalvanized options','Technical selection support']},
'wire-rope-slings':{title:'Wire Rope Slings',page:5,summary:'Safe, reliable and engineered for heavy lifting.',description:'Manufactured in single, two and four-leg configurations with soft eyes, thimble eyes and selected end fittings. Assemblies are identified for traceability and can be supplied with inspection documentation.',features:['Single, two and four-leg assemblies','Soft eye and thimble eye options','Ferrule-secured terminations','Proof-load testing available','Product identification and traceability']},
'chain-slings':{title:'Chain Slings',page:6,summary:'Grade 80 chain sling solutions for industrial lifting applications.',description:'Configured using compatible Grade 80 components and available in single, two and four-leg designs with hooks suited to the lifting task.',features:['Grade 80 chain and components','Single, two and four-leg designs','Grab hooks and self-locking hooks','Durable construction','Inspection and certification support']},
'webbing-slings':{title:'Webbing Slings',page:7,summary:'Lightweight polyester lifting slings with clear capacity identification.',description:'AllSafe webbing slings are designed for controlled handling and protection of the load surface. Multiple eye and endless configurations are available.',features:['Flat eye and twisted eye','Endless and return-eye designs','Colour coded for capacity','Lightweight and flexible','Custom lengths available']},
'round-slings':{title:'Round Slings',page:8,summary:'Flexible endless and heavy-duty round slings for safe material handling.',description:'Colour-coded polyester round slings provide flexibility around the load and straightforward capacity selection for many lifting applications.',features:['Endless and heavy-duty options','Colour-coded working load limits','Protective outer sleeve','Flexible load contact','Inspected and traceable']},
'endless-grommets':{title:'Endless Wire Rope Grommets',page:9,summary:'Heavy-duty endless grommets for critical lifting applications.',description:'Manufactured from high-quality wire rope to form a continuous lifting body, with configurations available for industrial, offshore, marine and construction lifts.',features:['Continuous endless construction','High strength and durability','Multiple diameters and capacities','Industrial and offshore applications','Proof-load testing available']},
'lifting-accessories':{title:'Lifting Accessories',page:10,summary:'Premium rigging hardware for safe and efficient lifting operations.',description:'A broad range of compatible lifting accessories for connection, adjustment and load control, selected to suit demanding site requirements.',features:['Shackles and hooks','Master links and connecting links','Eye bolts and turnbuckles','Load binders and accessories','Traceable certified options']},
'lifting-gears':{title:'Lifting Gears',page:11,summary:'Reliable material-handling solutions for industrial lifting applications.',description:'Manual lifting and positioning equipment for workshops, yards, construction sites and industrial operations.',features:['Chain blocks and lever hoists','Beam clamps and trolleys','Smooth and reliable operation','Durable industrial construction','Inspection support available']}}
const key=new URLSearchParams(location.search).get('id')||'wire-ropes',p=products[key]||products['wire-ropes'];document.title=`${p.title} | AllSafe`;document.querySelector('#title').textContent=p.title;document.querySelector('#summary').textContent=p.summary;document.querySelector('#description').textContent=p.description;document.querySelector('#pageImage').src=`assets/page-${String(p.page).padStart(2,'0')}.jpg`;document.querySelector('#pageImage').alt=`${p.title} catalogue page`;document.querySelector('#features').innerHTML=p.features.map(x=>`<li>${x}</li>`).join('');
